name: Deploy Static Website in s3
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist
      - name: list Artifacts
        run: ls
      - name: checkout custom action Code
        uses: actions/checkout@v4
      - name: Install Custom action deps
        uses: npm ci 
        working-directory: .github/actions/deploy-s3-javascript
      - name: deploy artifact
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        with:
          bucket: gha-custom-action-prac
          bucket-region: ap-south-1
          dist-folder: ./dist
      