name: First Workflow
on:
  workflow-dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      USERNAME: Nandan
    steps:
      - name: Checkout Code
        use: actions/checkout@v4
      - name: Run JS
        run: node hello.js