name: First Workflow
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      USER_NAME: ${{ vars.USER_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run JS
        run: node hello.js
      - name: Show env variable
        run: echo ${{ vars.USER_NAME}}