name: First Workflow
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run JS
        run: node hello.js
      - name: Show env variable
        run: echo ${{ env.USER_NAME}}