name: Matrix job
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 24] 
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: 26
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build